name: tflint --init & run
description: tflint --init & run

inputs:
  working-directory:
    description: chdir
    required: false
    default: "./terra"

runs:
  using: composite
  steps:
    - name: ls
      shell: bash
      run: ls ${{ inputs.working-directory }} -la

    - name: tflint --init
      shell: bash
      run: tflint --chdir ${{ inputs.working-directory }} --init

    - name: tflint
      shell: bash
      run: tflint --chdir ${{ inputs.working-directory }}
