#!/bin/bash

# TF_VAR_*
echo "TF_VAR_REPOSITORY_NAME = '${TF_VAR_REPOSITORY_NAME}'"
echo "TF_VAR_ENVIRONMENT = '${TF_VAR_ENVIRONMENT}'"

# ARM_ vars
echo "TF_VAR_ARM_LOCATION = '${TF_VAR_ARM_LOCATION}'"
