name: tflint

on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows
    inputs:
      working-directory:
        description: working-directory
        type: string
        required: false
        default: "./terra"

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    inputs:
      working-directory:
        description: chdir
        type: string
        required: false
        default: "./terra"

jobs:
  lint:
    runs-on: ubuntu-latest
    name: tflint
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main

      - uses: percebus/github-actions-tflint/.github/actions/setup@main

      # TODO
      # - uses: percebus/github-actions-tflint/.github/actions/init_and_run@main
      #   with:
      #     working-directory: ${{ inputs.working-directory }}

      # XXX vvv DELETE ME

      - name: ls
        run: ls ${{ inputs.working-directory }} -la

      - name: tflint --init
        run: tflint --chdir ${{ inputs.working-directory }} --init

      - name: tflint
        run: tflint --chdir ${{ inputs.working-directory }}

      # XXX ^^^ DELETE ME
